# Basic Information
title: Yang Zhang, Ph.D.
position: School of Information Sciences
affiliation: University of Illinois Urbana-Champaign
email: yzhangnd (at) illinois.edu

# Search Engine Optimization (SEO)
keywords: minimal light
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light-theme.yliu.me/

# Links
google_scholar: https://scholar.google.com/citations?user=uq55RBsAAAAJ
github_link: https://github.com/
linkedin: https://www.linkedin.com/in/yang-z-832aa3150/
cv_link: assets/files/curriculum_vitae.pdf
#twitter: https://twitter.com/

# Images
avatar: ./assets/img/yangzhang.jpg
favicon: ./assets/img/YZ.png
favicon_dark: ./assets/img/YZ.png

# Footnote
enable_footnote: true

# Theme Options
auto_dark_mode: true
font: "Serif"

# Google Analytics ID
google_analytics: UA-111540567-4

# Theme
remote_theme: yaoyao-liu/minimal-light

# Page Output Control
collections:
  pages:
    output: true
    permalink: /:name/

# Exclude from site build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
